linters-settings:
  lll:
    line-length: 200
issues:
  exclude-use-default: false
linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - gosimple
    - lll
    - staticcheck
    - revive
    - govet
    - goimports
run:
  deadline: 5m
